services:
  authservice:
    image: authservice
    ports:
      - "8001:8080"
    build:
      context: .
      dockerfile: Services/AuthService/Dockerfile

  auth_db:
    container_name: auth_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - MSSQL_SA_PASSWORD=admin_hr_flow123
      - ACCEPT_EULA=Y
    user: root
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - mssql_identity_data:/var/opt/mssql
        
volumes:
  mssql_identity_data: